pipelines:
  default:
    - step:
        name: Sync Bitbucket â†’ GitHub
        image: alpine/git:latest
        script:
          - git remote add github git@github.com:Gaurav2327/push-repo.git || true
          - git push github --all
          - git push github --tags
