image: atlassian/default-image:4

pipelines:
  target:
    main:
      - step:
          name: Push to GitHub
          script:
            - git remote add github git@github.com:Gaurav2327/push-repo.git || true
            - git push github --all
            - git push github --tags